# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: GitHub Self-Updating Repository for Todays Date and Weather
run-name: ${{ github.actor }} self-updating repository to tell you weather and date today 📅

on:
  # Schedule docs
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # At the beginning of every day.
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openmeteo-requests requests-cache retry-requests numpy pandas pytz

  # Create a directory IF it doesn't already exists
    - name: Create data directory
      run: mkdir -p data
        
    - name: Run main script
      run: python scripts/main.py
        
    - name: Commit and push changes repository
      run: |
        git config --global user.name "Christopher Escobar"
        git config --global user.email "105730846+wChrstphr@users.noreply.github.com"
        git add README.md data/weather_data.csv
        git commit -m "Automated push on $(date '+%m/%d/%Y %H:%M')"
        git push
